global using static Brayns.Shaper.Classes.Commons;
global using Functions = Brayns.Shaper.Classes.Functions;
global using Fields = Brayns.Shaper.Fields;
global using Brayns.Shaper.Objects;
global using Controls = Brayns.Shaper.Controls;
global using Error = Brayns.Shaper.Classes.Error;
global using PublicAccess = Brayns.Shaper.Classes.PublicAccessAttribute;
global using Published = Brayns.Shaper.Classes.PublishedAttribute;
global using LoggedAccess = Brayns.Shaper.Classes.LoggedAccessAttribute;
global using RunningTask = Brayns.Shaper.Objects.RunningTask;
global using Batch = Brayns.Shaper.Objects.Batch;
global using BatchMethod = Brayns.Shaper.Classes.BatchMethodAttribute;
global using ApiMethod = Brayns.Shaper.Classes.ApiMethodAttribute;
global using ApiAction = Brayns.Shaper.Classes.ApiAction;
global using Extended = Brayns.Shaper.Classes.ExtendedAttribute;
global using VirtualTable = Brayns.Shaper.Classes.VirtualTableAttribute;
global using ValuePerSession = Brayns.Shaper.Classes.ValuePerSessionAttribute;
global using CurrentSession = Brayns.Shaper.Session;
global using Label = Brayns.Shaper.Classes.LabelAttribute;
global using Newtonsoft.Json.Linq;
global using Client = Brayns.Shaper.Client;
global using Confirm = Brayns.Shaper.Systems.Confirm;
global using Message = Brayns.Shaper.Systems.Message;
global using Icon = Brayns.Shaper.Controls.Icon;
global using FilterLevel = Brayns.Shaper.Fields.FilterLevel;